[package]
name = "equation-exporter-tauri"
version = "0.1.4"
edition = "2024"

[build-dependencies]
tauri-build = { version = "2.6", features = [] }

[dependencies]
clipboard-rs = "0.3.5"
equation-exporter = { path = ".." }
tauri = { version = "2.11", features = [] }
tauri-plugin-dialog = "2"
url = "2.5.8"

[target.'cfg(target_os = "linux")'.dependencies]
gtk = "0.18.2"
